#!/usr/bin/env bash

PORT=5000
REPOSITORY=article-rec-api
DOCKER_OPTS=$(cat <<END_HEREDOC
    -v $HOME/.aws/credentials:/root/.aws/credentials:ro \
    -v $(pwd):/app \
    -p $PORT:$PORT \
    -e STAGE=local \
    -it $REPOSITORY
END_HEREDOC
)

#@cdk
#+Run cdk.
task-cdk() {
    (cd cdk && npx cdk $@)
}

#@build
#+Build docker image.
task-build() {
    docker build . -t $REPOSITORY
}

#@run
#+Run docker container.
task-run() {
    docker run $DOCKER_OPTS "$@"
}

#@flask
#+Run flask development server with automatic reloading.
task-flask() {
    # See: https://flask.palletsprojects.com/en/1.1.x/server/#server
    task-run flask run --host 0.0.0.0 --port $PORT --reload --debugger
}
