#!/usr/bin/env bash

PORT=5000
REPOSITORY=article-rec-api
DOCKER_OPTS=$(cat <<END_HEREDOC
    -v $HOME/.aws/credentials:/root/.aws/credentials:ro \
    -v $(pwd):/app \
    -p $PORT:$PORT \
    -e STAGE=local
END_HEREDOC
)

#@cdk
#+Run cdk.
task-cdk() {
    (cd cdk && npx cdk $@)
}

#@build
#+Build docker image.
task-build() {
    docker build . -t $REPOSITORY
}

#@run
#+Run docker container.
task-run() {
    # docker run $DOCKER_OPTS -it $REPOSITORY "$@"
    docker run $DOCKER_OPTS $REPOSITORY "$@"
}

#@test
#+Run tests.
task-test() {
    docker run $DOCKER_OPTS py.test tests
}
